### ISSUE TITLE
AttributeError: 'DetectionPredictor' object has no attribute 'all_outputs'

### ISSUE THREAD

**Issue by Mohamed3sam** [MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking#2]
[2023-01-19 11:46:32,799][root.tracker][INFO] - Loading weights from deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7... Done!
Ultralytics YOLOv8.0.7  Python-3.10.9 torch-1.13.1+cpu CPU
Fusing layers...
YOLOv8l summary: 268 layers, 43668288 parameters, 0 gradients, 165.2 GFLOPs
Error executing job with overrides: ['model=yolov8l.pt', 'source=test3.mp4', 'show=True']
Traceback (most recent call last):
  File "C:\Users\messam\Desktop\Project\YOLOv8-DeepSORT-Object-Tracking\ultralytics\yolo\v8\detect\predict.py", line 252, in predict
    predictor()
  File "C:\Users\messam\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\messam\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 160, in __call__
    return list(chain(*list(self.stream_inference(source, model, verbose))))  # merge list of Result into one
  File "C:\Users\messam\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 194, in stream_inference
    s += self.write_results(i, results, (p, im, im0))
  File "C:\Users\messam\Desktop\Project\YOLOv8-DeepSORT-Object-Tracking\ultralytics\yolo\v8\detect\predict.py", line 213, in write_results
    self.all_outputs.append(det)
AttributeError: 'DetectionPredictor' object has no attribute 'all_outputs'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by MuhammadMoinFaisal** [comment]
HI @Mohamed3sam, we have solved this issue please check and run the script again, Now you will not face this issue

Thanks
