### ISSUE TITLE
something wrong！  help

### ISSUE THREAD

**Issue by Liuchuang-alt** [MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking#26]
(deepsort) D:\download1\YOLOv8-DeepSORT-Object-Tracking-main\ultralytics\yolo\v8\detect>python predict.py model=yolov8l.pt source="test3.mp4" show=True
Traceback (most recent call last):
  File "predict.py", line 13, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
  File "d:\download1\yolov8-deepsort-object-tracking-main\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.hub import checks
  File "d:\download1\yolov8-deepsort-object-tracking-main\ultralytics\hub\__init__.py", line 10, in <module>
    from ultralytics.hub.auth import Auth
  File "d:\download1\yolov8-deepsort-object-tracking-main\ultralytics\hub\auth.py", line 5, in <module>
    from ultralytics.hub.utils import HUB_API_ROOT, request_with_credentials
  File "d:\download1\yolov8-deepsort-object-tracking-main\ultralytics\hub\utils.py", line 10, in <module>
    from ultralytics.yolo.utils import DEFAULT_CONFIG_DICT, LOGGER, RANK, SETTINGS, TryExcept, colorstr, emojis
  File "d:\download1\yolov8-deepsort-object-tracking-main\ultralytics\yolo\utils\__init__.py", line 400, in <module>
    SETTINGS = get_settings()
  File "d:\download1\yolov8-deepsort-object-tracking-main\ultralytics\yolo\utils\__init__.py", line 363, in get_settings
    root = get_git_root_dir() or Path('')  # not is_pip_package()
  File "d:\download1\yolov8-deepsort-object-tracking-main\ultralytics\yolo\utils\__init__.py", line 189, in get_git_root_dir
    output = subprocess.run(["git", "rev-parse", "--git-dir"], capture_output=True, check=True)
  File "D:\ProgramData\Anaconda3\envs\deepsort\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\ProgramData\Anaconda3\envs\deepsort\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\ProgramData\Anaconda3\envs\deepsort\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

(deepsort) D:\download1\YOLOv8-DeepSORT-Object-Tracking-main\ultralytics\yolo\v8\detect>python predict.py model=yolov8l.pt source="test3.mp4" show=True
Traceback (most recent call last):
  File "predict.py", line 13, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
  File "d:\download1\yolov8-deepsort-object-tracking-main\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.hub import checks
  File "d:\download1\yolov8-deepsort-object-tracking-main\ultralytics\hub\__init__.py", line 10, in <module>
    from ultralytics.hub.auth import Auth
  File "d:\download1\yolov8-deepsort-object-tracking-main\ultralytics\hub\auth.py", line 5, in <module>
    from ultralytics.hub.utils import HUB_API_ROOT, request_with_credentials
  File "d:\download1\yolov8-deepsort-object-tracking-main\ultralytics\hub\utils.py", line 10, in <module>
    from ultralytics.yolo.utils import DEFAULT_CONFIG_DICT, LOGGER, RANK, SETTINGS, TryExcept, colorstr, emojis
  File "d:\download1\yolov8-deepsort-object-tracking-main\ultralytics\yolo\utils\__init__.py", line 400, in <module>
    SETTINGS = get_settings()
  File "d:\download1\yolov8-deepsort-object-tracking-main\ultralytics\yolo\utils\__init__.py", line 363, in get_settings
    root = get_git_root_dir() or Path('')  # not is_pip_package()
  File "d:\download1\yolov8-deepsort-object-tracking-main\ultralytics\yolo\utils\__init__.py", line 189, in get_git_root_dir
    output = subprocess.run(["git", "rev-parse", "--git-dir"], capture_output=True, check=True)
  File "D:\ProgramData\Anaconda3\envs\deepsort\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\ProgramData\Anaconda3\envs\deepsort\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\ProgramData\Anaconda3\envs\deepsort\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,None, None,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

(deepsort) D:\download1\YOLOv8-DeepSORT-Object-Tracking-main\ultralytics\yolo\v8\detect>python predict.py model=yolov8l.pt source="test3.mp4" show=True
Traceback (most recent call last):
  File "predict.py", line 13, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
  File "d:\download1\yolov8-deepsort-object-tracking-main\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.hub import checks
  File "d:\download1\yolov8-deepsort-object-tracking-main\ultralytics\hub\__init__.py", line 10, in <module>
    from ultralytics.hub.auth import Auth
  File "d:\download1\yolov8-deepsort-object-tracking-main\ultralytics\hub\auth.py", line 5, in <module>
    from ultralytics.hub.utils import HUB_API_ROOT, request_with_credentials
  File "d:\download1\yolov8-deepsort-object-tracking-main\ultralytics\hub\utils.py", line 10, in <module>
    from ultralytics.yolo.utils import DEFAULT_CONFIG_DICT, LOGGER, RANK, SETTINGS, TryExcept, colorstr, emojis
  File "d:\download1\yolov8-deepsort-object-tracking-main\ultralytics\yolo\utils\__init__.py", line 400, in <module>
    SETTINGS = get_settings()
  File "d:\download1\yolov8-deepsort-object-tracking-main\ultralytics\yolo\utils\__init__.py", line 363, in get_settings
    root = get_git_root_dir() or Path('')  # not is_pip_package()
  File "d:\download1\yolov8-deepsort-object-tracking-main\ultralytics\yolo\utils\__init__.py", line 189, in get_git_root_dir
    output = subprocess.run(["git", "rev-parse", "--git-dir"], capture_output=True, check=True)
  File "D:\ProgramData\Anaconda3\envs\deepsort\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\ProgramData\Anaconda3\envs\deepsort\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\ProgramData\Anaconda3\envs\deepsort\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,None, None,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by FengZhongLiuDong** [comment]
请问你解决了吗
