### ISSUE TITLE
how to train my own dataset

### ISSUE THREAD

**Issue by AlphaGoooo** [MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking#34]
hello, the pretrained model(yolov8l.pt) didn't fit my dataset, so I want to train on my own dataset. But I don't know how to train it, could you give me some advice? Thanks.

**Comment by Abhijeet241093** [comment]
Did you found the way ?

**Comment by Abhijeet241093** [comment]
[2024-03-18 20:54:18,878][root.tracker][INFO] - Loading weights from deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7... Done!
Ultralytics YOLOv8.0.3 🚀 Python-3.8.18 torch-2.2.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060, 12029MiB)
Error executing job with overrides: ['model=best.pt', 'source=output_video.mp4', 'show=True']
Traceback (most recent call last):
  File "predict.py", line 326, in predict
    predictor()
  File "/home/tricubics/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/tricubics/YOLOv8-DeepSORT-Object-Tracking/ultralytics/yolo/engine/predictor.py", line 164, in __call__
    model = self.model if self.done_setup else self.setup(source, model)
  File "/home/tricubics/YOLOv8-DeepSORT-Object-Tracking/ultralytics/yolo/engine/predictor.py", line 121, in setup
    model = AutoBackend(model, device=device, dnn=self.args.dnn, fp16=self.args.half)
  File "/home/tricubics/YOLOv8-DeepSORT-Object-Tracking/ultralytics/nn/autobackend.py", line 73, in __init__
    model = attempt_load_weights(weights if isinstance(weights, list) else w,
  File "/home/tricubics/YOLOv8-DeepSORT-Object-Tracking/ultralytics/nn/tasks.py", line 303, in attempt_load_weights
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "/home/tricubics/.local/lib/python3.8/site-packages/torch/serialization.py", line 1026, in load
    return _load(opened_zipfile,
  File "/home/tricubics/.local/lib/python3.8/site-packages/torch/serialization.py", line 1438, in _load
    result = unpickler.load()
  File "/home/tricubics/.local/lib/python3.8/site-packages/torch/serialization.py", line 1431, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'ultralytics.nn.modules.conv'; 'ultralytics.nn.modules' is not a package

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by EshoneLee** [comment]
> [2024-03-18 20:54:18,878][root.tracker][INFO] - Loading weights from deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7... Done! Ultralytics YOLOv8.0.3 🚀 Python-3.8.18 torch-2.2.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060, 12029MiB) Error executing job with overrides: ['model=best.pt', 'source=output_video.mp4', 'show=True'] Traceback (most recent call last): File "predict.py", line 326, in predict predictor() File "/home/tricubics/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/home/tricubics/YOLOv8-DeepSORT-Object-Tracking/ultralytics/yolo/engine/predictor.py", line 164, in **call** model = self.model if self.done_setup else self.setup(source, model) File "/home/tricubics/YOLOv8-DeepSORT-Object-Tracking/ultralytics/yolo/engine/predictor.py", line 121, in setup model = AutoBackend(model, device=device, dnn=self.args.dnn, fp16=self.args.half) File "/home/tricubics/YOLOv8-DeepSORT-Object-Tracking/ultralytics/nn/autobackend.py", line 73, in **init** model = attempt_load_weights(weights if isinstance(weights, list) else w, File "/home/tricubics/YOLOv8-DeepSORT-Object-Tracking/ultralytics/nn/tasks.py", line 303, in attempt_load_weights ckpt = torch.load(attempt_download(w), map_location='cpu') # load File "/home/tricubics/.local/lib/python3.8/site-packages/torch/serialization.py", line 1026, in load return _load(opened_zipfile, File "/home/tricubics/.local/lib/python3.8/site-packages/torch/serialization.py", line 1438, in _load result = unpickler.load() File "/home/tricubics/.local/lib/python3.8/site-packages/torch/serialization.py", line 1431, in find_class return super().find_class(mod_name, name) ModuleNotFoundError: No module named 'ultralytics.nn.modules.conv'; 'ultralytics.nn.modules' is not a package
> 
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

I also encountered the same problem. Have you solved it?

**Comment by Thomas-CHOCHOY** [comment]
Same, have you solved it?
