### ISSUE TITLE
ImportError: cannot import name 'DeepSort' from 'deep_sort_pytorch.deep_sort' (unknown location)

### ISSUE THREAD

**Issue by NhanDoremon** [MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking#44]
After I unzip the deep_sort_pytorch zip file, and i run the code like:     !python predict.py source="test1.mp4"     
The model have the problem below, i reall appreciate if you help me to sovle it, thank you in advance
Traceback (most recent call last):
  File "d:\OneDrive - Sejong University\NgheNhan_Master\Course Work\First Semester\Advanced in Machine Vision\Projects\Abnormal Behavior\Code\Object_detection_and Tracking\YOLOv8-DeepSORT-Object-Tracking\ultralytics\yolo\v8\detect\predict.py", line 14, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
  File "d:\onedrive - sejong university\nghenhan_master\course work\first semester\advanced in machine vision\projects\abnormal behavior\code\object_detection_and tracking\yolov8-deepsort-object-tracking\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.hub import checks
  File "d:\onedrive - sejong university\nghenhan_master\course work\first semester\advanced in machine vision\projects\abnormal behavior\code\object_detection_and tracking\yolov8-deepsort-object-tracking\ultralytics\hub\__init__.py", line 15, in <module>
    from ultralytics.yolo.v8.detect import DetectionTrainer
  File "d:\onedrive - sejong university\nghenhan_master\course work\first semester\advanced in machine vision\projects\abnormal behavior\code\object_detection_and tracking\yolov8-deepsort-object-tracking\ultralytics\yolo\v8\detect\__init__.py", line 3, in <module>
    from .predict import DetectionPredictor, predict
  File "d:\onedrive - sejong university\nghenhan_master\course work\first semester\advanced in machine vision\projects\abnormal behavior\code\object_detection_and tracking\yolov8-deepsort-object-tracking\ultralytics\yolo\v8\detect\predict.py", line 23, in <module>
    from deep_sort_pytorch.deep_sort import DeepSort
ImportError: cannot import name 'DeepSort' from 'deep_sort_pytorch.deep_sort' (unknown location)

**Comment by Sakura0v01** [comment]
Have you solved this problem?If so, how was it resolved

**Comment by NhanDoremon** [comment]
Yes I already fixed this problem, I think the source code is lack of deep_sort_pytorch module. So I find this module on another repo and add to the forlder "./v8/detect". If you need this module, please contact me through my email ***@***.***, i will send you the zip file of that module because of the large size so I can't send directly in github.
________________________________
