### ISSUE TITLE
ModuleNotFoundError: No module named 'ultralytics.nn.modules.conv'; 'ultralytics.nn.modules' is not a package

### ISSUE THREAD

**Issue by Abhijeet241093** [MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking#49]
When retrained your model yolov8l.pt with custom dataset and then used best. pt for prediction it giving following errors: 
ModuleNotFoundError: No module named 'ultralytics.nn.modules.conv'; 'ultralytics.nn.modules' is not a package
!python predict.py model=yolov8l.pt source="output_video.mp4" show=True 

[2024-03-18 20:54:18,878][root.tracker][INFO] - Loading weights from deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7... Done!
Ultralytics YOLOv8.0.3 🚀 Python-3.8.18 torch-2.2.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060, 12029MiB)
Error executing job with overrides: ['model=best.pt', 'source=output_video.mp4', 'show=True']
Traceback (most recent call last):
  File "predict.py", line 326, in predict
    predictor()
  File "/home/tricubics/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/tricubics/YOLOv8-DeepSORT-Object-Tracking/ultralytics/yolo/engine/predictor.py", line 164, in __call__
    model = self.model if self.done_setup else self.setup(source, model)
  File "/home/tricubics/YOLOv8-DeepSORT-Object-Tracking/ultralytics/yolo/engine/predictor.py", line 121, in setup
    model = AutoBackend(model, device=device, dnn=self.args.dnn, fp16=self.args.half)
  File "/home/tricubics/YOLOv8-DeepSORT-Object-Tracking/ultralytics/nn/autobackend.py", line 73, in __init__
    model = attempt_load_weights(weights if isinstance(weights, list) else w,
  File "/home/tricubics/YOLOv8-DeepSORT-Object-Tracking/ultralytics/nn/tasks.py", line 303, in attempt_load_weights
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "/home/tricubics/.local/lib/python3.8/site-packages/torch/serialization.py", line 1026, in load
    return _load(opened_zipfile,
  File "/home/tricubics/.local/lib/python3.8/site-packages/torch/serialization.py", line 1438, in _load
    result = unpickler.load()
  File "/home/tricubics/.local/lib/python3.8/site-packages/torch/serialization.py", line 1431, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'ultralytics.nn.modules.conv'; 'ultralytics.nn.modules' is not a package

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by reach-the-peak** [comment]
did you solve it？

**Comment by Jahsleh** [comment]
Same problem, has anyone solved it yet?

**Comment by WindyHu001** [comment]
same problem too.

**Comment by hjdasioh** [comment]
Did someone take  it？

**Comment by FEIAFR11** [comment]
How can I solve it?

**Comment by TanXi789** [comment]
You'll have to retrain in yolov8-deepsosrt to get best.pt files

**Comment by theway0139** [comment]
> You'll have to retrain in yolov8-deepsosrt to get best.pt files

how to do

**Comment by Thomas-CHOCHOY** [comment]
Same, have you solved it?

**Comment by Eggplant-11** [comment]
have you solved it?
